# Generated by Django 6.0.5 on 2026-05-16 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Empunhadura',
                'verbose_name_plural': 'Empunhaduras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('blade', models.CharField(max_length=80)),
                ('forehand_rubber', models.CharField(max_length=80)),
                ('backhand_rubber', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Estilo',
                'verbose_name_plural': 'Estilos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/photos/')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nome')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Idade')),
                ('dominant_hand', models.CharField(choices=[('R', 'Destro'), ('L', 'Canhoto')], max_length=1, verbose_name='Mao dominante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.club', verbose_name='Clube')),
                ('grip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.grip', verbose_name='Empunhadura')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.material', verbose_name='Material')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.style', verbose_name='Estilo')),
            ],
            options={
                'verbose_name': 'Perfil de atleta',
                'verbose_name_plural': 'Perfis de atletas',
                'ordering': ['full_name'],
            },
        ),
    ]
