# Generated by Django 6.0.5 on 2026-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/'),
        ),
    ]
