# Generated by Django 6.0.5 on 2026-05-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_club_abbreviation_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='abbreviation',
            new_name='short_name',
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nome curto'),
        ),
    ]
