# Generated by Django 6.0.5 on 2026-05-16 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_rename_age_to_birth_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Competicao')),
            ],
            options={
                'verbose_name': 'Competicao',
                'verbose_name_plural': 'Competicoes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_one_name', models.CharField(max_length=120, verbose_name='Atleta 1')),
                ('athlete_two_name', models.CharField(max_length=120, verbose_name='Atleta 2')),
                ('match_date', models.DateField(verbose_name='Data da partida')),
                ('video_file', models.FileField(upload_to='matches/videos/%Y/%m/%d/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athletes.competition', verbose_name='Competicao')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_match_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video de partida',
                'verbose_name_plural': 'Videos de partidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
