# Generated by Django 6.0.5 on 2026-05-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_seed_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchvideo',
            name='athlete_one_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_videos_as_athlete_one', to='athletes.athleteprofile', verbose_name='Atleta 1 (cadastro)'),
        ),
        migrations.AddField(
            model_name='matchvideo',
            name='athlete_two_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_videos_as_athlete_two', to='athletes.athleteprofile', verbose_name='Atleta 2 (cadastro)'),
        ),
    ]
