# Generated by Django 6.0.5 on 2026-05-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_matchvideo_athlete_one_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome do adversario')),
            ],
            options={
                'verbose_name': 'Adversario',
                'verbose_name_plural': 'Adversarios',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='matchvideo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descricao do video'),
        ),
        migrations.AddField(
            model_name='matchvideo',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_videos', to='athletes.opponent', verbose_name='Adversario'),
        ),
    ]
