# Generated by Django 6.0.5 on 2026-05-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_opponent_matchvideo_description_matchvideo_opponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('start_match', 'Inicio da partida'), ('score_update', 'Atualizacao de placar')], max_length=20)),
                ('video_time_seconds', models.FloatField(default=0)),
                ('time_signature', models.CharField(max_length=20)),
                ('set_athlete_one', models.PositiveSmallIntegerField(default=0)),
                ('set_athlete_two', models.PositiveSmallIntegerField(default=0)),
                ('point_athlete_one', models.PositiveSmallIntegerField(default=0)),
                ('point_athlete_two', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_game_actions', to=settings.AUTH_USER_MODEL)),
                ('match_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_actions', to='athletes.matchvideo')),
            ],
            options={
                'verbose_name': 'Acao de jogo',
                'verbose_name_plural': 'Acoes de jogo',
                'ordering': ['created_at'],
            },
        ),
    ]
