# Generated by Django 6.0.5 on 2026-05-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0010_matchgameaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMarkerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de marcador',
                'verbose_name_plural': 'Tipos de marcadores',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_marker_types(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='matchgameaction',
            name='action_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='matchgameaction',
            name='marker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_actions', to='athletes.matchmarkertype'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_marker_types(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _seed_marker_types(apps):
    MatchMarkerType = apps.get_model('athletes', 'MatchMarkerType')

    marker_rows = [
        {'code': 'start_game', 'name': 'Inicio de jogo', 'color': '#126e52', 'icon': '▶', 'sort_order': 1},
        {'code': 'first_to_fifth_ball', 'name': '1ª a 5ª bola', 'color': '#2f6fdb', 'icon': '⑤', 'sort_order': 2},
        {'code': 'point_my', 'name': 'Ponto meu', 'color': '#e5a100', 'icon': '↑', 'sort_order': 3},
        {'code': 'point_opponent', 'name': 'Ponto do adversario', 'color': '#b42318', 'icon': '↓', 'sort_order': 4},
        {'code': 'technical_timeout', 'name': 'Tempo tecnico', 'color': '#7a4dbf', 'icon': '⏱', 'sort_order': 5},
    ]

    for row in marker_rows:
        MatchMarkerType.objects.update_or_create(code=row['code'], defaults=row)


def _backfill_marker_types(apps):
    MatchGameAction = apps.get_model('athletes', 'MatchGameAction')
    MatchMarkerType = apps.get_model('athletes', 'MatchMarkerType')

    marker_map = {marker.code: marker for marker in MatchMarkerType.objects.all()}
    default_marker = marker_map.get('start_game') or next(iter(marker_map.values()), None)

    for action in MatchGameAction.objects.select_related('match_video').all():
        marker_type = marker_map.get(action.action_type)
        if marker_type is None:
            marker_type = default_marker
        if marker_type is not None:
            action.marker_type_id = marker_type.id
            action.action_type = marker_type.code
            action.save(update_fields=['marker_type', 'action_type'])
