# Generated by Django 6.0.5 on 2026-05-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0016_add_match_set_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchvideo',
            name='opponent',
        ),
    ]
